### ISSUE TITLE
Link Issue on Profile

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/github-graphs#16]
When people have URLs in their Github profiles, unless they include "http" or "https", the link is considered relative to local to github-graphs.com.

![oops](https://user-images.githubusercontent.com/13894625/71276873-d35a6b80-2322-11ea-919b-0c5e0843f8fe.PNG)

![2](https://user-images.githubusercontent.com/13894625/71277481-11f02600-2323-11ea-88fd-cfe78820d51b.PNG)

**Comment by petermorgandev** [comment]
Do you have an example of a GitHub user to test this with?

**Comment by jrtechs** [comment]
@PeterMorganGH you can test it with this user: https://github-graphs.com/FriendsGraph.html?name=Balake-weasel

If you want to work on this that would be great! This is the file that needs to get changed:
https://github.com/jrtechs/github-graphs/blob/master/public/js/profileGen.js

Let me know if you have any other questions.

**Comment by petermorgandev** [comment]
@jrtechs Thank you for providing the link. I have an idea of how to solve this issue and will see if it works.

**Comment by petermorgandev** [comment]
Should this issue be closed due to https://github.com/jrtechs/github-graphs/pull/17?

**Comment by jrtechs** [comment]
closed #17
