### ISSUE TITLE
Improve Performance of Friends Graph

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/github-graphs#20]
We want to better utilize how we are caching things on the backend for the friends of friends graph. The JSON that the GitHub API returns has a ton of URL's that are either redundant or unnecessary for this project. I also want to reduce the number of calls between the front end and the backend GitHub proxy server.

![Screenshot_2019-12-26_13-29-35](https://user-images.githubusercontent.com/13894625/71486654-6abd3400-27e5-11ea-92f4-8624773990a5.png)

**Comment by petermorgandev** [comment]
In reworking the backend API, it should be possible to filter out any data that isn't needed before passing it on to the user.

**Comment by jrtechs** [comment]
yep, that's the plan! It should also be possible to make the cache size on the back end a lot smaller

**Comment by jrtechs** [comment]
I'm starting to work on this issue in this branch: 
https://github.com/jrtechs/github-graphs/tree/friends-graph-improvement

Things left to do:
- minimize JSON stored
- rewrite frontend js to use new backend route
- improve performance of pagination [performance](https://developer.github.com/v3/guides/traversing-with-pagination/)

I hope to have this done tomorrow/this weekend.

**Comment by petermorgandev** [comment]
@jrtechs You might want to use a routing system like the following. That way someone can go to `https://github-graphs.com/api/jrtechs` and get the JSON data for user `jrtechs`.
```javascript
router.get("/:username", <your_function>);
```

**Comment by jrtechs** [comment]
@PeterMorganGH that would be ideal. We can make our own restful API of sorts.
