### ISSUE TITLE
Null Name Case

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/github-graphs#23]
Most people on github have both a username and real name set and it looks like this:

![name](https://user-images.githubusercontent.com/13894625/71529902-2dc07280-28b5-11ea-9eb0-f088deb6aed2.png)

However, some people only have a username set but no name. Currently, we are displaying the name as null where we should just display the username instead. 

![nullName](https://user-images.githubusercontent.com/13894625/71529904-2ef19f80-28b5-11ea-8e28-3b840757f925.png)

Example:
https://github-graphs.com/TimeLineGraph.html?name=CetaceanNation

We should also be setting the max-width of the profile image to 100%. 

File to change:
https://github.com/jrtechs/github-graphs/blob/master/public/js/profileGen.js

**Comment by petermorgandev** [comment]
I think you could do this for now before the front end is redone:

```javascript
${user.name ? `<h5 class="card-title mb-1">${user.name}</h5>` : ""}
```

**Comment by jrtechs** [comment]
@PeterMorganGH I think that would work, do you want to do a quick PR for it?

**Comment by petermorgandev** [comment]
@jrtechs I currently have a PR open on @ct-martin's fork. I am not sure how different forks work with different PRs, but I will see if I can get another one opened with this change.

**Comment by jrtechs** [comment]
closed in #24

**Comment by ct-martin** [comment]
@PeterMorganGH thank you! I somehow didn't get an email for that, will take a look today.

**Comment by petermorgandev** [comment]
@ct-martin No worries. With the holidays I didn't expect a quick review of the PR. I was traveling myself, but I intend to work on it some more this weekend.
