### ISSUE TITLE
Website Facelift

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/github-graphs#3]
I'm looking for any reasonable website page redesigns that improve appearance. Things that help accessibility, and mobile layout would be nice. I don't want people to entirely re-design the website in react or another JS framework. Simply modifying the vanilla HTML and bootstrap code would be enough.

**Comment by pepas24** [comment]
Hey @jrtechs I'll like to help here! How can I proceed?

**Comment by jrtechs** [comment]
@pepas24 Run the program, go to the website and see if there is anything you would like to change to make it look better. If you are unsure about any of your ideas, you can drop them in this issue and I can let you know what I think about it.

**Comment by pepas24** [comment]
Thanks, I'll start to work on it!

**Comment by pepas24** [comment]
Hi @jrtechs I made this mockup for the project, I want to know what do you think about this design before start with the markup.
[https://figma.fun/3kRC8q](https://figma.fun/3kRC8q)

**Comment by jrtechs** [comment]
@pepas24 That looks absolutely amazing! You have my permission to start working on this. If you want, feel free to break this up over a few pull requests.

**Comment by pepas24** [comment]
Hi @jrtechs I advanced with home page and generator page you can take a look on my [fork](https://github.com/pepas24/github-graphs/tree/improvement/ui-redesign). Tomorrow I'll make a pull request. But some parts of other pages don't are well displayed because I removed some styles.

**Comment by jrtechs** [comment]
@pepas24 Sounds great.

**Comment by pepas24** [comment]
Hi @jrtechs since the past weekend I'm getting "user not exists" in all my requests, I noticed that some times works and others don't, I've checked out to master branch to test it and I've got the same error. Do you know what can be the problem? I can't finish the design that way :/

**Comment by jrtechs** [comment]
@pepas24 I know what the issue is. In the config.json file add the following line:

```  
"user": "jrtechs",
```

replace jrtechs with your github username.

**Comment by pepas24** [comment]
Thanks that works!

**Comment by jrtechs** [comment]
closed in #4
