### ISSUE TITLE
Take environment variables for config

### ISSUE THREAD

**Issue by ct-martin** [jrtechs/github-graphs#7]
Environment variables w/o a file-based config are standard for many PaaS hosting platforms

**Comment by jrtechs** [comment]
We currently just have basic configurations stored in the config.json file for the Github api, port, etc. What other environment variables are you referring to? Or, are you suggesting we change the config.js to a node .env environment file?

**Comment by ct-martin** [comment]
@jrtechs system environment variables, e.g. `FOO=BAR npm start` and `process.env`

Related (don't have to use):
https://www.npmjs.com/package/dotenv
https://www.npmjs.com/package/cross-env

**Comment by petermorgandev** [comment]
I have used dotenv before. It is a lot easier to use it for configuration than the way config.js is set up.

**Comment by jrtechs** [comment]
@PeterMorganGH if you could transition the config.js and config.json files into dotenv that would be amazing!

**Comment by petermorgandev** [comment]
I should be able to implement dotenv. I don't know how you have https://github-graphs.com hosted, but you may need to tweak the .env file based on your hosting setup.

**Comment by jrtechs** [comment]
@PeterMorganGH the .env files as you put them work great! I am simply hosting this application on a DigitalOcean droplet. Digitalocean

**Comment by petermorgandev** [comment]
@jrtechs In the [pull request to fix this issue](https://github.com/jrtechs/github-graphs/pull/18) @ct-martin said: 

> CLIENT_ID is your GitHub username and the CLIENT_SECRET is a personal access token

Is that correct or did you have to register this as a GitHub app? I just ran into the rate limit while reworking the API.

**Comment by ct-martin** [comment]
I didn't thoroughly test that; I might not have hit the rate limit when I
did it... I figured it'd throw a 403 if I got it wrong but maybe not. Sorry
if I caused confusion

--
Christian Martin (Phone)

**Comment by petermorgandev** [comment]
@ct-martin It's all good. I just did something else for a while until GitHub's API let me access it again. I managed to finish my refactor. I am in the process of opening a PR for its approval from @jrtechs.

**Comment by jrtechs** [comment]
@ct-martin I have only noticed a 403 on two certain profiles. It is weird, I can't really figure out why it is happening since GH doesn't provide any clear example of why you would get throttled. I'll open an issue for this, maybe we could handle the 403 better.
